/**
 * Location domain model, digested from the legacy grid data
 * (data/maps/allGrids.js, generated by tools/convert_maps.py from the
 * original Java map PNGs). See old_src/maps/allGrids.ts for the raw shape.
 *
 * The legacy data is 63 flat grids ("maps"), each a sparse list of tiles —
 * width/height is a bounding box, not every (x,y) inside it has a tile.
 * Some tiles carry a `travelConfig` pointing at a tile on another grid
 * (stairs, doorways, map-edge exits). Those links form a tree: most grids
 * have exactly one incoming link and so one natural parent map, e.g.
 *   WORLD_MAP -> DOMINION -> SLAVER_ALLEY -> BOUNTY_HUNTER_LODGE -> BOUNTY_HUNTER_LODGE_UPSTAIRS
 * A minority of grids (apartments, dream sequences, bonus dungeons) have no
 * travel links at all — the original game teleports into them directly from
 * event/dialogue code rather than from a map tile, so they have no parent
 * here either; they're still valid roots, just not nested under anything.
 *
 * `Location` is deliberately not a bag of ids/coordinates: a `Location` can
 * only be built by pointing at a `MapTile` that's actually stored on some
 * `GameMap`, so "is this map/x/y combination real, and can you be there" is
 * answered by construction rather than by a separate check. The parent
 * chain works the same way — `GameMap.parent` is a `Travel` built from the
 * literal source tile, not a string id you'd have to re-resolve and could
 * get wrong.
 *
 * `GameMap` and `World` own their state privately (tile-by-coordinate index,
 * the map registry) and expose it only through query methods/readonly
 * views; both are built up in stages by `World.build()` (tiles must all
 * exist before travel links can be resolved, which must happen before the
 * parent tree can be walked), so their mutating methods are `@internal` —
 * meant for that construction process, not for callers once a `World` exists.
 */

/** Raw shapes as emitted by tools/convert_maps.py into allGrids.js. */
export interface RawTravelConfig {
  travelType: string;
  label: string;
  nextLocationName: string;
  nextGridName: string;
  coords: { x: number; y: number };
}

export interface RawPlace {
  name: string;
  color: string;
  placeType: string;
  passage: string;
  description?: string;
}

export interface RawTile {
  x: number;
  y: number;
  location: RawPlace;
  travelConfig?: RawTravelConfig;
}

export interface RawGridMeta {
  id: string;
  name: string;
  width: number;
  height: number;
  tiles: number;
}

export type RawGrids = Record<string, RawTile[]>;
export type RawGridMetaMap = Record<string, RawGridMeta>;

/** What a tile is — immutable, so a plain value class with a named factory. */
export class Place {
  private constructor(
    readonly id: string,
    readonly name: string,
    readonly color: string,
    readonly passage: string,
    readonly description?: string,
  ) {}

  static from(raw: RawPlace): Place {
    return new Place(raw.placeType, raw.name, raw.color, raw.passage, raw.description);
  }
}

/** A validated destination: `to` is a real tile on a real map. */
export interface Travel {
  to: Location;
  /** "Enter" / "Exit" / "To" / "World map" — from the legacy travelConfig. */
  label: string;
}

export class MapTile {
  private _travel: Travel | null = null;

  constructor(
    readonly x: number,
    readonly y: number,
    readonly place: Place,
  ) {}

  /** Set if stepping onto this tile can lead to another map (a doorway/stairs/map edge). */
  get travel(): Travel | null {
    return this._travel;
  }

  /** @internal set once, while World resolves travelConfig links during construction. */
  setTravel(travel: Travel): void {
    this._travel = travel;
  }
}

/** One flat grid ("map"). */
export class GameMap {
  private readonly _tiles: MapTile[] = [];
  private readonly _byCoord = new Map<string, MapTile>();
  private readonly _children: GameMap[] = [];
  private _parent: Travel | null = null;

  constructor(
    readonly id: string,
    readonly name: string,
    readonly width: number,
    readonly height: number,
  ) {}

  get tiles(): readonly MapTile[] {
    return this._tiles;
  }

  /** Maps entered from a tile on this one. */
  get children(): readonly GameMap[] {
    return this._children;
  }

  /** The tile (on some other map) you pass through to enter this one; null for a root/standalone map. */
  get parent(): Travel | null {
    return this._parent;
  }

  /** The tile at (x, y), or undefined — this is a sparse grid, not every in-bounds coordinate is occupied. */
  tileAt(x: number, y: number): MapTile | undefined {
    return this._byCoord.get(GameMap.coordKey(x, y));
  }

  /** @internal */
  addTile(tile: MapTile): void {
    this._tiles.push(tile);
    this._byCoord.set(GameMap.coordKey(tile.x, tile.y), tile);
  }

  /** @internal */
  setParent(parent: Travel): void {
    this._parent = parent;
  }

  /** @internal */
  addChild(child: GameMap): void {
    this._children.push(child);
  }

  private static coordKey(x: number, y: number): string {
    return x + ',' + y;
  }
}

/**
 * An exact, load-bearing location: this specific tile, on this specific
 * map. Because `tile` always comes from `map`'s own tiles, a `Location` can
 * never point at coordinates that don't exist — there's no separate "is
 * this actually on the map" question to ask once you have one.
 *
 * `map.parent` (recursively) gives you the full root-to-leaf chain for
 * free — see `breadcrumbs()` for a flattened, display-friendly view of it.
 */
export class Location {
  constructor(
    readonly map: GameMap,
    readonly tile: MapTile,
  ) {}

  /**
   * Root-first map ids from this location's map.parent chain, this map's id
   * last. Derived from the validated structure, not the other way around —
   * don't build a `Location` from one of these, build it with `World#locate`.
   */
  breadcrumbs(): string[] {
    const ids: string[] = [];
    let map: GameMap | undefined = this.map;
    const seen = new Set<string>();
    while (map && !seen.has(map.id)) {
      ids.unshift(map.id);
      seen.add(map.id);
      map = map.parent?.to.map;
    }
    return ids;
  }
}

/** The full set of maps digested from the legacy grid data, and the tree linking them. */
export class World {
  private readonly _maps: ReadonlyMap<string, GameMap>;

  /** Maps with no parent: either true tree roots (WORLD_MAP) or standalone
   * maps entered directly by game code instead of via a tile link. */
  readonly roots: readonly GameMap[];

  /** Legacy travelConfig entries that pointed at a map/tile that doesn't
   * exist in this data — dropped rather than trusted. Empty on clean data. */
  readonly warnings: readonly string[];

  private constructor(maps: ReadonlyMap<string, GameMap>, warnings: string[]) {
    this._maps = maps;
    this.warnings = warnings;
    this.roots = [...maps.values()].filter((m) => m.parent === null);
  }

  getMap(id: string): GameMap | undefined {
    return this._maps.get(id);
  }

  /**
   * Looks up an exact location, validating that (x, y) is actually a tile
   * on that map. Returns undefined — not a best-effort guess — if the map
   * doesn't exist or has no tile there, i.e. "you can't be there".
   */
  locate(mapId: string, x: number, y: number): Location | undefined {
    const map = this._maps.get(mapId);
    const tile = map?.tileAt(x, y);
    return map && tile ? new Location(map, tile) : undefined;
  }

  /** All tiles across the world whose place id matches. */
  findByPlaceType(placeType: string): Location[] {
    const results: Location[] = [];
    for (const map of this._maps.values()) {
      for (const tile of map.tiles) {
        if (tile.place.id === placeType) results.push(new Location(map, tile));
      }
    }
    return results;
  }

  /**
   * Builds the nested map/sub-map tree from the legacy flat grid data.
   * Takes the already-parsed allGrids/LT_GRID_META objects (however they
   * get loaded — no dependency on the legacy window globals).
   */
  static build(rawGrids: RawGrids, rawMeta: RawGridMetaMap): World {
    const maps = new Map<string, GameMap>();
    for (const meta of Object.values(rawMeta)) {
      maps.set(meta.id, new GameMap(meta.id, meta.name, meta.width, meta.height));
    }

    // Phase 1: create every tile (travel left unresolved) and index it by
    // coordinate, so phase 2 can look up destination tiles by real object,
    // not by trusting the raw x/y a travelConfig claims.
    const pendingTravel: { tile: MapTile; mapId: string; raw: RawTravelConfig }[] = [];
    for (const [gridId, rawTiles] of Object.entries(rawGrids)) {
      const map = maps.get(gridId);
      if (!map) continue; // no meta entry — shouldn't happen with well-formed data
      for (const raw of rawTiles) {
        const tile = new MapTile(raw.x, raw.y, Place.from(raw.location));
        map.addTile(tile);
        if (raw.travelConfig) pendingTravel.push({ tile, mapId: gridId, raw: raw.travelConfig });
      }
    }

    // Phase 2: resolve travelConfig into validated Travel/Location values
    // now that every map's tiles exist to check against.
    const warnings: string[] = [];
    for (const { tile, mapId, raw } of pendingTravel) {
      const destMap = maps.get(raw.nextGridName);
      const destTile = destMap?.tileAt(raw.coords.x, raw.coords.y);
      if (!destMap || !destTile) {
        warnings.push(
          `${mapId} (${tile.x},${tile.y}) "${raw.label}" travels to ${raw.nextGridName} ` +
            `(${raw.coords.x},${raw.coords.y}), which doesn't exist — dropped`,
        );
        continue;
      }
      tile.setTravel({ to: new Location(destMap, destTile), label: raw.label });
    }

    // Phase 3: BFS to assign each map's parent from the first validated
    // travel link that reaches it. This has to be a proper BFS with a
    // visited set, not a single pass in object-key order: most maps link
    // back to their parent (an "Exit" tile pointing the other way), and a
    // linear pass would let that back-edge re-parent the parent once it
    // reaches the child's tiles. BFS guarantees each map is discovered —
    // and parented — only once, by whichever map reaches it first.
    const visited = new Set<string>();
    for (const startId of maps.keys()) {
      if (visited.has(startId)) continue;
      visited.add(startId);
      const queue: string[] = [startId];
      while (queue.length) {
        const currentId = queue.shift()!;
        const current = maps.get(currentId)!;
        for (const tile of current.tiles) {
          const dest = tile.travel;
          if (!dest || visited.has(dest.to.map.id)) continue;
          visited.add(dest.to.map.id);
          dest.to.map.setParent({ to: new Location(current, tile), label: dest.label });
          queue.push(dest.to.map.id);
        }
      }
    }

    for (const map of maps.values()) {
      if (map.parent) maps.get(map.parent.to.map.id)?.addChild(map);
    }

    return new World(maps, warnings);
  }
}
